# Generated by Django 4.2.7 on 2025-05-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_produto_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='Produto',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='image',
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0),
        ),
    ]
